### ISSUE TITLE
Cannot attach docker container with `debugger` while `pry.binding` can

### ISSUE THREAD

**Issue by eggplants** [ruby/debug#1013]
**Your environment**

* `ruby -v`: `ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-darwin22]`
* `rdbg -v`: `rdbg 1.8.0 {:mode=>:start, :no_color=>nil}`

**Describe the bug**

I tried to set breakpoint within Rails constroller:

```rb
class FooController < ApplicationController
  def create
    ...
    debugger
  end
end
```

And then I ran `docker compose up` and sent request to the method with `curl`. After launching debugger, I couldn't attach to the container process running rails service by `docker attach bar-web-1`.

Interestingly, I then installed `pry-byebug` and replaced `debugger` with `pry.binding` and was able to attach without problems.

No one else seemed to have this problem　on the web, so I could be doing something wrong.

**To Reproduce**
TBD

**Expected behavior**
User must be able to attach with `docker attach` even if degug gem's debugger is launched.

**Additional context**
TBD

**Comment by ko1** [comment]
I have no idea about it.
Have you verified that `debugger` method is invoked?

**Comment by eggplants** [comment]
Yes. The debug gem's debugger has shown in docker console when runtime ruby has reached the `debugger` line.

**Comment by ko1** [comment]
Let me clear the repro process.

* 1. (D(ocker)) docker run with detached mode
* 2. (D) Rails server starts
* 3. (C(lient)) curl
* 4. (D) `debugger` method is invoked
* 5. (C) `docker attach`

Questions:

* please correct me if the process is wrong.
* and what happens after (5)?
* How to invoke rails server in docker container?
* Could you repro with simple ruby program instead of Rails program?

Thanks,
Koichi

**Comment by eggplants** [comment]
Thank you. I'll create MRE code soon.
