### ISSUE TITLE
Improvement: "help" cmd output -- MD render needed

### ISSUE THREAD

**Issue by williamhatch** [ruby/debug#296]
@ko1 @olleolleolle @st0012 current type "help" cmd it shows like:

(rdbg) help    # command
### Control flow

* `s[tep]`
  * Step in. Resume the program until next breakable point.
* `s[tep] <n>`
  * Step in, resume the program at `<n>`th breakable point.
* `n[ext]`
  * Step over. Resume the program until next line.
* `n[ext] <n>`
  * Step over, same as `step <n>`.
* `fin[ish]`

do we plan to show it use Markdown render or it is by design?

If we want to do `help` showing more friendly (Markdown render etc) I can help :)

Please let me know.

**Comment by ko1** [comment]
Could you show me the example output?

**Comment by williamhatch** [comment]
> Could you show me the example output?

@ko1 https://github.com/piotrmurach/tty-markdown check this :)

What do you think?

**Comment by ko1** [comment]
we can't use the library because it will be bundled with Ruby itself.
external extension (debug-md-help, for example) is okay.

**Comment by svoop** [comment]
@ko1 I don't quite understand what you mean with:

> external extension (debug-md-help, for example) is okay.

Wouldn't it be possible to use a renderer if it is installed and continue to show raw markdown otherwise? Here's another renderer btw:

https://github.com/ttscoff/mdless

Another possible approach: Add a development rake task to the debug gem which translates MD files to a terminal output bytestream (using one of the renderers) and then include this compiled MD when the gem is released. This way, no runtime dependency is necessary and you still get the comfort of MD when authoring and colored, nice output when displaying the help.

**Comment by ko1** [comment]
@ko1 I don't quite understand what you mean with:
> external extension (debug-md-help, for example) is okay.

I meant "we can't accept to make dependency to other gems, but if you make another gem named `debug-md-help` for example, and it extend debug.gem to make help prettier with markdown gems, no problem."

> Wouldn't it be possible to use a renderer if it is installed and continue to show raw markdown otherwise?

It is another option.

> Another possible approach: Add a development rake task to the debug gem which translates MD files to a terminal output bytestream (using one of the renderers) and then include this compiled MD when the gem is released. This way, no runtime dependency is necessary and you still get the comfort of MD when authoring and colored, nice output when displaying the help.

Yes, it is another option.
