### ISSUE TITLE
binding.b doesn't stop code on spring process after the second time

### ISSUE THREAD

**Issue by willnet** [ruby/debug#319]
**Your environment**

- Ruby 3.0.2
- Rails 6.1.4.1
- debug 1.2.4
- spring 3.0.0

**Describe the bug**

binding.b doesn't stop code on spring process after the second time

**To Reproduce**

```
rails new debug-sample
cd debug-sample
bundle add debug --version 1.2.4
bin/rails r 'binding.b' #=> stop at railties-6.1.4.1/lib/rails/commands/runner/runner_command.rb:45
bin/rails r 'binding.b' #=> it doesn't stop, it ends.
```

**Expected behavior**

`binding.b` works at any time.

**Comment by ko1** [comment]
Now spring is not supported.

* Debugger is only activated on ONE process from fork parent/children.
  * On the default, child process activates the debugger at fork, and deactivate the parent process.
  * Because if two or more processes enter the debug console simultaneously, it should be mixed output/input.
  * For example, if it uses 2 or more worker processes, it can be an confusion.
  * Maybe you can see debugger's message (activate/deactivate).
* spring is not supported because:
  * spring makes another process at first, the child process activates the debugger and spring parent process deactivates.
  * on the next process, the parent process deactivated the debugger, so that second child process doesn't activate the debugger.

I understand this is an issue, but now I have no idea how to solve it. One idea is to introduce lock file mechanism between processes and allows activates debuggers multiple processes. Another idea is to open remote debuggers for all child processes.

**Comment by willnet** [comment]
I found that binding.b doesn't stop the code in system test(system spec) in Rails for the same reason, so I'd like to report it.

I think it's because system test(system spec) uses fork to run chromedriver, so the process on chromedriver side is active and it doesn't stop.

## to reproduce


rails new system-test-sample
cd system-test-sample
bundle add debug --version 1.2.4
bundle remove spring --install
bin/rails db:migrate
bin/rails g controller welcome index
edit config/routes.rb like following

```ruby
Rails.application.routes.draw do
  root 'welcome#index'
end
```

bin/rails g system_test welcome

edit test/system/welcomes_test.rb like following

```ruby
require "application_system_test_case"

class WelcomesTest < ApplicationSystemTestCase
  test "visiting top page" do
    visit root_path
    binding.b # it doesn't stop but `binding.irb` stop.
  end
end
```

bin/rails test:system
