### ISSUE TITLE
The default debugger for Ruby?

### ISSUE THREAD

**Issue by st0012** [ruby/debug#5]
I'm really interested in this gem and I'd like to contribute to it. But I also need to learn more about it to make the correct contribution. So here are my questions:

- Is the goal to make it Ruby's default debugger?
- What's its difference between tools like `pry` and `byebug`? Like, are we replacing them and porting some of their useful features here? Or we're going to make them configurable options for some of the features (like breakpoint)?
- Is there a plan to add test cases to it? I may be able to help with this at the beginning.

**Comment by ko1** [comment]
> I'm really interested in this gem and I'd like to contribute to it. But I also need to learn more about it to make the correct contribution. So here are my questions:

Thank you for interest for this gem.

> * Is the goal to make it Ruby's default debugger?

Yes. It will be merged with Ruby 3.1 (by replacing lib/debug.rb).

> * What's its difference between tools like `pry` and `byebug`? Like, are we replacing them and porting some of their useful features here? Or we're going to make them configurable options for some of the features (like breakpoint)?

I'm not sure about your concern, but we can accept useful features after discussion.

The advantage of this library from ruby 3.1, we don't need to write anything in Gemfile (because it will be a default gem), using `pry` is not good approach. We are considering to integrate with irb, but not sure because of irb's command implementation policy.

I'm happy to hear about the feedbacks.

> * Is there a plan to add test cases to it? I may be able to help with this at the beginning.

One person is trying to make a tests.

**Comment by st0012** [comment]
@ko1 thanks for all the answers!

> Yes. It will be merged with Ruby 3.1 (by replacing lib/debug.rb).

wow I didn't know there's already a debugger inside Ruby 

> I'm not sure about your concern, but we can accept useful features after discussion.

I just dug into the codebase and I think many of the features I want have been implemented (with different names). So this is like a dumb question 😅 

> One person is trying to make a tests.

Good to hear that. I'd like to contribute to tests when they're available 😄
