### ISSUE TITLE
 `sourceReference` is always set to 1 even though a local (matching) source is available

### ISSUE THREAD

**Issue by jonatan-branting** [ruby/debug#697]
There is an issue where `debug` will always set `sourceReference = 1` even though a local source is available and matches the source according to the debugger.

I tried implementing a fix for this on the client side, but it does indeed not seem to be the job for the client: https://github.com/mfussenegger/nvim-dap/pull/602

This causes issues such as a less seamless experience as well as constant creation of unnamed buffers/windows which have to be manually closed.

Edit: Is there even a reference to how the server *should* act in this case? i.e. when to set `sourceReference`?

_Originally posted by @jonatan-branting in https://github.com/ruby/debug/issues/692#issuecomment-1179553397_

**Comment by ko1** [comment]
Please write your environment, what's happens, what is the expected behavior and reproducible steps.

I guess:

* You are using nvim-dap and connect to the DAP server with TCP/IP
* When debuggee stops at a breakpoint, nvim shows readonly source code because of `sourceReference = 1`. Mabye in the response of `StackTrace`. Maybe you only do not try other files, so `sourceReference` can be other numbers.
* expected: `sourceReference` should be 0 because it runs on the same machine.

Please correct me if they are wrong.

The answer is:

* Using TCP/IP we can not recognize it is same host so debug.gem assumes remote fs and local fs are different.
* To solve that, please try `RUBY_DEBUG_LOCAL_FS_MAP` envnval with `RUBY_DEBUG_LOCAL_FS_MAP=/:/` for debuggee.

**Comment by jonatan-branting** [comment]
Thanks for the very detailed response (and sorry about the lack of environment details)! You hit the nail on the head, that was the exact scenario.

Setting `RUBY_DEBUG_LOCAL_FS_MAP` (or rather, passing `localfs=true`) worked perfectly, and this is indeed not an issue.

**Comment by ko1** [comment]
ah, can you pass `localfs=true`?
I never success to use nvim-dap with debug.gem, so step-by-step guide for non-nvim user (== me) will be very helpful!!!

**Comment by jonatan-branting** [comment]
Hey!

I can add that, although I'll probably postpone it a bit as the ecosystem is still a bit WIP. 

What makes it a bit more complicated than for other DAPs is the requirement of using TCP/IP to integrate with `nvim-dap`. For this reason, this plugin has been created: https://github.com/suketa/nvim-dap-ruby

I had some issues integrating that plugin with another plugin called `neotest`, so for this reason I'm currently using the code in this gist (in case you were personally interested!) https://gist.github.com/jonatan-branting/73ce57974f8f3643d4c15655d14c12c2

Something to note is that `nvim-dap` will pass anything from a given configuration to the debugee, which is why `localfs = true` worked.

**Comment by ko1** [comment]
Hey, nvim newbe (== me) does not know how to write any configurations :p
So this is why I wrote *step-by-step guide*.

Anyway, I wait for such kind tutorial when the eco system matured.

**Comment by jonatan-branting** [comment]
Haha, that's true, got a bit carried away I reckon!

I'll write a step-by-step guide once the ecosystem has matured :)
