### ISSUE TITLE
list variables in sorted order to make navigation easier

### ISSUE THREAD

**Issue by dscherger-stripe** [ruby/debug#798]
**Your proposal**
When debugging ruby in vscode the variables are displayed in seemingly random order which makes it difficult to locate a specific variable when the list is long. It would be helpful and hopefully easy to display this list in sorted order.

**Additional context**

<img width="236" alt="image" src="https://user-images.githubusercontent.com/74793898/201192625-8dd344b1-bf4b-44f6-9fa6-0bd68c50d710.png">

**Comment by ko1** [comment]
I see. simple `sort` works?

**Comment by wenderjean** [comment]
It seems we're not able to search variables in VSCode like we usually do in the console with `info c /my_variable/` even though I think it might be useful for the `info` command in general, I mean, not only for the VSCode addon.

**Comment by ko1** [comment]
> It seems we're not able to search variables in VSCode like we usually do in the console with info c /my_variable/

Yes. I'm thinking to support debug command on the debug console. This is different idea so I'll make new issue or PR.

BTW I think it is better that the debug console should support only Ruby REPL (not accept debug commands) because VSCode (or IDE) has GUI buttons for step/next/.... and `i` should show the variable `i` (not `info` command).
So I'm thinking to support escape character such as `#` and `#i c /pat/` runs `i c /pat/` command. Current problem is which character is better for the escaping.

**Comment by wenderjean** [comment]
@ko1 Do you think the simple sort is useful? It sounds to me like a good first issue. I'd like to give it a try.
